### ISSUE TITLE
Missing API methods, as well as some missing parameters

### ISSUE THREAD

**Issue by LikeLakers2** [meew0/discordrb#309]
Hi there, whilst browsing discordapp.com's API section, I happened to notice some methods that had parameters that could be specified, that do not have equivalent parameters in discordrb's API modules. So I went through, and *hoo boy* have I found quite a lot. I even found some API endpoints that do not have an equivalent API module method. So have a list.

Where possible, I do not take into account the reason (if any may exist) that a method may not have a parameter. I simply looked if the official API documentation and discordrb had the same parameters available for use.

### Missing parameters
- [x] `API::Channel.messages`, missing `around_id` parameter -- #314
- [x] `API::Channel.create_message`, missing `nonce` parameter -- #414 
- [x] `API::Channel.create_invite`, missing `unique` parameter -- #312
- [x] `API::Server.update`, missing `verification_level`, `default_message_notifications`, ~~`owner_id`~~, `splash` parameters -- #414 
- [x] `API::Server.create_channel`, missing `bitrate`, `user_limit`, `permission_overwrites` parameters -- #321 
- [x] `API::Server.create_role`, missing `name`, `permissions`, `color`, `hoist`, `mentionable` parameters -- #323 
- [x] `API::Server.prune_count`, missing `days` parameter -- #315

### Missing API module equivalents
As mentioned, I have found several API endpoints documented on Discord's API documentation that do not have an equivalent in discordrb's API modules.

Guild:
- [x] [Add Guild Member](https://discordapp.com/developers/docs/resources/guild#add-guild-member) --
 #413 
- [x] [Add Guild Member Role](https://discordapp.com/developers/docs/resources/guild#add-guild-member-role)/[Remove Guild Member Role](https://discordapp.com/developers/docs/resources/guild#remove-guild-member-role) -- #310
- [x] [Modify Guild Role Positions](https://discordapp.com/developers/docs/resources/guild#modify-guild-role-positions) -- #445
- [x] [Get Guild Voice Regions](https://discordapp.com/developers/docs/resources/guild#get-guild-voice-regions) -- #311 
- [x] [Get Guild Embed](https://discordapp.com/developers/docs/resources/guild#get-guild-embed)/[Modify Guild Embed](https://discordapp.com/developers/docs/resources/guild#modify-guild-embed) -- #435 
- [x] Abstraction for `API::Server.invites` -- #394 
- [x] `ServerBan` or `Ban` class that supports `reason` and `#remove` for lifting bans -- #404 

Channels:
- [x] Abstraction for `API::Channel.invites` -- #394 

Voice:
- [x] [List Voice Regions](https://discordapp.com/developers/docs/resources/voice#list-voice-regions) -- #311

### Misc
Since this is a issue all about API stuff, I'll throw a couple other things in regarding existing API methods.
- [x] `API::Channel.bulk_delete_messages` -- Change the URL used to use `bulk-delete` instead of the apparently deprecated `bulk_delete`. -- 5a3a2105454596b5380de3c35deace0a615f5219
- [x] `API::User.query` -- I noticed that the link related to this no longer points to an existing API endpoint documentation, thus I believe this no longer works. -- 1b8a6d173d41f86b589c4ee034a4baecf77e9a1f

Sorry for the long issue, I just figured I'd dump all this into one issue since they're all related!

**Comment by z64** [comment]
Thanks for looking into this. As mentioned, a lot of these were known, but haven't been changed because no one has really needed / asked for them, so haven't really had a reason to. The way things are now may reflect that they were written when some of those fields or endpoints didn't exist at the time they were written. 

Anyway, some other details, going over ;

- `API::Server.create_channel` missing things

Looking at adding this myself, I have a branch for it. as this is something I need, actually.

- Add Guild Member

I don't believe a `Bot` token has the scope to do this. 
A bot can't really make someone join a server, at least only in the context of Discord - requires an Oauth application scope per the docs - think of the page that you use to add bots to your server, like that.)
No idea how that stuff is implemented ; never seen it used, nor what a use case would be besides creating some kind of app that has you join a server following signing up for a forum.

- Add/Remove guild member role

These are new. Should be pretty easy, whoever does it takes mind to re-implement the new endpoint into the existing `data.rb` abstractions that make use of it.

- Modify Current User's Nick

This already exists. 

http://www.rubydoc.info/gems/discordrb/Discordrb%2FAPI%2FUser.change_own_nickname

- Modify Guild Role Positions

I believe this has been avoided being implemented for some time because of possible issues with it. I can't quite remember, but this isn't the first time its been brought up and we passed on it for one reason or another. I'm sure meew would remember.

- `API::Server.update`

`owner_id` - I think its not possible to update this, unless the guild is managed by an integration perhaps. (Only the owner can change the server owner)

`splash` - Only applies to partnered servers. 

- Get Guild Embed, Modify Guild Embed

This is already implicitly covered by the open #202 issue. This stuff is a bother to test by nature and no one seems to really care about it that uses discordrb.

**Comment by LikeLakers2** [comment]
In regards to all of these, I recommend at least putting an API module method for those that don't exist -- we can worry about making the appropriate methods in their classes later -- such that those who may actually need them don't have to type out their own methods. Whether we can implement actual functionality for them in other classes should **not** be a requirement to add them to the API modules.

* Modify Current User's Nick -- My bad, this one was listed under "Guild" in the Discord API docs, and so I looked at `API::Server` for this. While it's not necessarily a requirement, I suggest maybe moving it to Server, to keep in line with the official docs.

* `API::Server.update` -- Whatever the case may be, `owner_id` is still listed in the official docs, so I imagine there's *some* way to do it. And `splash` is also there, but I don't know what else to say about that.

**Comment by z64** [comment]
>Whatever the case may be, owner_id is still listed in the official docs, so I imagine there's some way to do it. And splash is also there, but I don't know what else to say about that.

My comments were just remarks about these parameters, nothing to do with whether they or possible, or if they should be implemented or not in drb. 

It is possible if the client is the owner of the guild - which would only really ever be the case for selfbots.

**Comment by z64** [comment]
Just did a quick search about `API::User.query`

> Remove query user endpoint from docs
> It's actually been gone since August.

https://github.com/hammerandchisel/discord-api-docs/commit/b1fc2435ccd817a5b7b68fbcac5f6d523fc244ae

So, this can indeed be removed.

**Comment by z64** [comment]
A few other things to add:

- [ ] Abstraction for `API::Server.invites`
- [ ] Abstraction for `API::Channel.invites`
- [ ] `ServerBan` or `Ban` class that supports `reason` and `#remove` for lifting bans

**Comment by z64** [comment]
Thanks to everyone who participated in this issue. :smile: 

To anyone watching this issue, for future "missing" things, either at the API binding or abstraction level, please open an individual issue or PR for that one feature.
